[package]
name = "wasm_test"
version = "0.1.2"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.1.0"
physsol = { git = "https://github.com/nthend/physsol-rs", rev = "a3828f215c9161a4b375b58ad3f77a05b8aa7816" }
